### ISSUE TITLE
Custom CSS is crippled -- also, make custom CSS for highlight filters possible

### ISSUE THREAD

**Issue by NoneGiven** [4chan/4chan-JS#59]
A while ago I wrote a bit of custom CSS to turn spoilers into colored text. I was using Stylish at the time, but I tried the same code out in 4chan's inline CSS option, and it worked great.

Now I can't seem to get half the things I try to work. Things as simple as body {text-decoration:blink!important} do nothing!

But for another example, let's take the highlighting by filter option. I wanted to see if it was possible to do different things to filtered posts based on which "color" I had specified they should be highlighted it was. Using Stylish, I've done some of the following...

``` css
.filter-hl {
box-shadow:none!important;
}
//Get rid of the actual highlight
.post.reply.filter-hl[style="box-shadow: -3px 0px red;"] .postMessage {
text-decoration:blink!important;
}
//Blinking red text for "red" highlighted replies
.filter-hl[style="box-shadow: -3px 0px rgb(236, 206, 245);"] {
font-family:"Comic Sans MS",cursive,sans-serif!important;
}
//Comic Sans for all posts highlighted by #ECCEF5
```

Since the filter allows any HTML color code, that's over 16 million different kind of highlighting CSS one could potentially apply. This all works perfectly in Stylish.

Not so in the inline's CSS box. I can do the first step (using the filter-hl class to remove all highlights), but there doesn't appear to be any way to use existing style to differentiate between filters. They're all in the same class, and appending the [style="whatever"] seems to be ignored by the inline. I don't believe it used to be this way, because a while back I managed to target a specific 4chan Pass notice by specifying its style.

So, two possible suggestions:
1. Allow the inline to recognize the [style="blah"] bit, which can differentiate between differently-colored instances of the filter-hl class
2. Do what 4chan X does, and allow a custom class name to be assigned along with a given filter

Thank you for your time.
